### ISSUE TITLE
Does not honor defaultOnly flag

### ISSUE THREAD

**Issue by cswl** [sw-yx/barrelbot#3]
```
barrelbot watch src --extension ts --namespace defaultOnly
```

Results in
```
// THIS FILE IS AUTOGENERATED AND MANAGED BY BARRELBOT. DO NOT EDIT

// for more info: https://github.com/sw-yx/barrelbot
export * from './macros.tsx'
```

**Comment by swyxio** [comment]
hey,

thanks for filing this issue - i am busy now but will be happy to look at PRs - otherwise i will wait until i work on a barrel heavy project again :)

**Comment by bushmango** [comment]
I looked into this because I was trying to get `--namespace all' to work like defaultOnly above, and when I cloned the repository it worked fine! But when I use the npm package it has some issues. I think that maybe you just forgot to publish the latest version to npm?

**Comment by swyxio** [comment]
oh is that so! ok i'll check on this, thank you @bushmango. obviously i havent been updating this very much as its just kinda worked well on my machine heh. gimme a sec

**Comment by swyxio** [comment]
i have published as v0.0.6 - it should be exactly what is in github now https://github.com/sw-yx/barrelbot/releases/tag/v0.0.6

**Comment by bushmango** [comment]
Thanks! I forked to add disabling of tslint and eslint as well

**Comment by swyxio** [comment]
you're welcome to contribute if you like! inviting you as contributor.
